### PR TITLE
Updated File Structure and Added Makefile 

### PR DESCRIPTION
**Pull request by SuperChamp234**
- The file structure is now according to #48
- Added Makefile to project root.
- This Makefile can `build FOLDER=<subfolder_name>` for building `*cpp` files in a subfolder and link openCV libraries.
- It can `install` openCV libraries in Debian, Arch, and MacOS.
- It can also do utilities like `run` and `clean`.
- All executable files are stored in `bin` folder, while all build files are stored in `<subfolder>/build` folder.

### CODE REVIEW

**Comment by amanchhaparia** [comment]
@SuperChamp234, also add the folders(empty) for the remaining topics, as described in #48

**Comment by aPR0T0** [comment]
@amanchhaparia so should we wait for the empty folders to be added on the main branch through this Pull request because after that only we could make our changes and issue PR

**Review by amanchhaparia — CHANGES_REQUESTED** [review]
- Add numbering to the subfolder e.g. `4_cv_basics/1_image_representation`
- Add `1_cpp_basics` folder
- Update with appropriate `Readme.md` under `2_build_systems`

**Comment by SuperChamp234** [comment]
@amanchhaparia All suggested changes have been made, please check.

**Pull request merged**
