### PR TITLE
Port to C++: Morphological Operations

### PR DESCRIPTION
**Pull request by Asc91**
In reference to issue #50 
Added examples 
    1. erosion
    2. dilation
    3. opening
    4. closing
    5. gradient

Added helper functions
   1. erosion
   6. dilation
   7. difference

Added readme similar to previous year's [morphology](https://github.com/SRA-VJTI/Pixels_Seminar/blob/main/3_cv_basics/4_morphology.ipynb).

### CODE REVIEW

**Comment by Ris-Bali** [comment]
Please use a proper naming convention for all files eg: algorithm.hpp and algo.cpp instead of using main.cpp and helper.hpp for every algorithm.

**Comment by Asc91** [comment]
Renamed main.cpp to 'algo'.cpp
No changes made to helper.hpp as it's contents are same in all folders.

**Comment by Ris-Bali** [comment]
Use a single helper.hpp then instead of multiple copies of the same file

**Comment by Smit1603** [comment]
- Above commit had some major changes like ,
- 1] Generalised modules for different kernel size
- 2] Modified code with proper documentation and modified file structure as suggested by @Ris-Bali 
- 3] Added module for performing padding

Kindly review

**Review by amanchhaparia — CHANGES_REQUESTED** [review]
Break the paragraphs in `readme.md`. And avoid putting theory paragraphs continuously.

**Review by amanchhaparia — APPROVED** [review]

**Comment by advait-0** [comment]
Can you add usage instructions to the morphology readme?
It'll be easier to replicate it's usage then at any time.

**Pull request merged**
