### PR TITLE
Uniform Makefiles for all programs with Usage instructions

### PR DESCRIPTION
**Pull request by advait-0**
I've updated and tested makefiles and added usage instructions to the README's of the corresponding programs,
The idea was to keep it simple and uniform while not breaking it's dependencies
It has the following 3 commands common to all the programs:
1. make build
2. make run
3. make clean
So as to not make it confusing and/or overwhelming for first time C++ OpenCV users

### CODE REVIEW

**Comment by advait-0** [comment]
Makefiles and instrunctions for the following are yet to be added:
1_image_representation
3_interpolation

which i'll add as soon as I can

**Comment by aPR0T0** [comment]
And have you remamed all code in subfolders as main.cpp? - For uniformity

**Comment by advait-0** [comment]
It's as per the original file structure, you don't need to type the file names, so it doesn't matter anyways.

**Comment by advait-0** [comment]
> Makefiles and instrunctions for the following are yet to be added: 
~~1_image_representation~~
~~3_interpolation~~
> 
>~ which i'll add as soon as I can~

Added support for all Makefiles

**Pull request closed without merging**
